config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: null
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColQwen2_5_Processor
    pretrained_model_name_or_path:  "./models/colqwen2.5-base"
    max_num_visual_tokens: 1536

  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColQwen2_5
    mask_non_image_embeddings: true
    pretrained_model_name_or_path: "./models/colqwen2.5-base"
    torch_dtype:  !ext torch.bfloat16
    use_cache: false
    attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  # dataset_loading_func: !ext colpali_engine.utils.dataset_transformation.load_train_set
  dataset_loading_func: 
    (): colpali_engine.utils.dataset_transformation.load_train_set
    ds_paths:
      # - ./data_dir/colpali_train_set pdf,docvqa,tatdqa
      - ./data_dir/VisRAG/VisRAG-Ret-Train-In-domain-data all
      # - ./data_dir/VisRAG/VisRAG-Ret-Train-Synthetic-data all
      - ./data_dir/Visual-CoT docvqa,textcap,textvqa,infographicsvqa
  eval_dataset_loader: !import ../data/debug_data.yaml

  # max_length: 50
  run_eval: true
  loss_func:
    (): colpali_engine.loss.late_interaction_losses.RegionContraLoss
    global_tau: 0.02
    local_tau: 0.25
    pos_threshold: 0
    local_coef: 0.01
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: false
    num_train_epochs: 5
    per_device_train_batch_size: 80
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    # gradient_accumulation_steps: 4
    per_device_eval_batch_size: 64
    eval_strategy: "steps"
    dataloader_num_workers: 8
    bf16: true
    save_steps: 200
    logging_steps: 1
    eval_steps: 200
    warmup_steps: 100
    learning_rate: 2e-4
    save_total_limit: 20
    resume_from_checkpoint: true
    # optim: "paged_adamw_8bit"
    # wandb logging
    # wandb_project: "colqwen2"
    # run_name: "colqwen2-ba32-nolora"
    report_to: "tensorboard"


  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'

